"""Added shirt size

Revision ID: 62a2af84b28d
Revises: d1a00822bc48
Create Date: 2024-08-31 10:24:34.101759

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62a2af84b28d"
down_revision: Union[str, None] = "d1a00822bc48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel",
        sa.Column("shirt_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usermodel", "shirt_size")
    # ### end Alembic commands ###
